services:
  nayeon-pokemon:
    image: "nayeon-pokemon"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - POKEMON_CHANNEL=${POKEMON_CHANNEL}
      - CRON_JOB_HOURS=${CRON_JOB_HOURS}
      - SPECIFIED_USER_ID=${SPECIFIED_USER_ID}
